
<div class="col-md-2 col-sm-2 col-md-offset-1 box0" >
                  		<div class="box1">
                                    <a href="<?=BASE_URL?>index/managetag" style="color:#989898;">
                                    <span class="fa fa-tags" aria-hidden="true"></span>
					<h4>Manage Tag</h4>
                                    </a>
                  		</div>
					  		
                  		</div>
                  	
                  		<div class="col-md-2 col-sm-2 box0">
                  			<div class="box1">
                                            <a href="<?=BASE_URL?>index/managetime" style="color:#989898;">
                                            <span class="fa fa-calendar" aria-hidden="true"></span>
                                            <h4>Manage Time</h4>
                                            </a>
                  			</div>
					  			
                  		</div>
                  		<div class="col-md-2 col-sm-2 box0">
                  			<div class="box1">
                                            <a href="<?=BASE_URL?>index/report" style="color:#989898;">
					  	<span class="fa fa-bar-chart-o"></span>
					  	<h4>Report</h4>
                                            </a>
                  			</div>
					
                  		</div>
